on:
  [push]
name: deb11 - Build OpenCV 4.9.0 (no cuda)
jobs:
  testbuild:
    name: Building OpenCV
    runs-on: ubuntu-latest
    steps:
      - name: Check out the build script repository
        uses: actions/checkout@master
      - name: Execute build script
        uses: ./ci-tests/deb11-4.9.0-nocuda
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}
