on:
  [push]
name: deb12 - Build OpenCV 4.9.0 (no cuda)
jobs:
  testbuild-deb12-nocuda:
    name: Building OpenCV
    runs-on: ubuntu-latest
    steps:
      - name: Check out the build script repository
        uses: actions/checkout@master
      - name: Make scripts executable
        run: chmod +x "ci-tests/deb12-4.9.0-nocuda/entrypoint.sh"
      - name: Execute build script
        uses: ./ci-tests/deb12-4.9.0-nocuda
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-deb12-nocuda
          path: ${{ github.workspace }}/libopencv-titanian-nocuda_4.9.0-1+deb12-1_amd64.deb
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/libopencv-titanian-nocuda_4.9.0-1+deb12-1_amd64.deb
          asset_name: libopencv-titanian-nocuda_4.9.0-1+deb12-1_amd64.deb
          tag: ${{ github.ref }}
          overwrite: true
          body: "OpenCV 4.9.0 built for deb12"
